name: Wordbahn
favicon: null
layout_spectrum: 0.33253287291154265
typography_spectrum: 0.63936
title: Wordbahn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5eff1'
    - '#1c3c55'
    - '#fcb535'
    - '#94a2a3'
    - '#9a674c'
  brandStrength: 0.7366812292020768
  lightness: 0.3735109129920602
  saturation: 0.255668715108186
  rhythmicContrast: 0.7977962165605277
purpose: []
